replicaCount: 1

image:
  repository: ""        # will be overridden from CI: e.g. $CI_REGISTRY_IMAGE
  tag: "latest"
  pullPolicy: IfNotPresent
  # if your registry is private and you created an imagePullSecret in the cluster set its name here:
  pullSecretName: ""

service:
  type: ClusterIP
  port: 8000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
